"use client";

import { useState } from "react";
import Hero from "@/components/Hero";
import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import EmailCaptureForm from '../components/EmailCaptureForm';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      
      <main className="flex-grow">
        {/* Hero Section */}
        <section className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white py-20">
          <div className="container mx-auto px-4 text-center">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6">
              Unlock the Power of AI with InnoGenius.ai
            </h1>
            <p className="text-xl md:text-2xl mb-8 max-w-3xl mx-auto">
              AI-powered tools to enhance your productivity, creativity, and workflow.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4">
              <Link href="/features" className="bg-white text-indigo-600 hover:bg-gray-100 py-3 px-8 rounded-lg font-semibold text-lg transition-colors">
                Explore Features
              </Link>
              <Link href="/pricing" className="bg-transparent hover:bg-white/10 border-2 border-white py-3 px-8 rounded-lg font-semibold text-lg transition-colors">
                View Pricing
              </Link>
            </div>
          </div>
        </section>
        
        {/* Features Overview */}
        <section className="py-16 bg-gray-50">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">Our AI-Powered Tools</h2>
              <p className="text-xl text-gray-600 max-w-2xl mx-auto">
                Discover how our suite of AI tools can transform your workflow and boost your productivity.
              </p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {/* AI Humanizer */}
              <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
                <div className="p-6">
                  <div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold mb-2">AI Humanizer</h3>
                  <p className="text-gray-600 mb-4">
                    Transform AI-generated text into natural, human-like content that passes AI detection tools.
                  </p>
                  <Link href="/features/humanizer" className="text-indigo-600 hover:text-indigo-800 font-medium">
                    Learn more →
                  </Link>
                </div>
              </div>
              
              {/* AI Text Detector */}
              <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
                <div className="p-6">
                  <div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path>
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold mb-2">AI Text Detector</h3>
                  <p className="text-gray-600 mb-4">
                    Verify if text was generated by AI with our advanced detection tool with high accuracy.
                  </p>
                  <Link href="/features/detector" className="text-indigo-600 hover:text-indigo-800 font-medium">
                    Learn more →
                  </Link>
                </div>
              </div>
              
              {/* AI CV Writer */}
              <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
                <div className="p-6">
                  <div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold mb-2">AI CV & Cover Letter</h3>
                  <p className="text-gray-600 mb-4">
                    Create professional CVs and cover letters tailored to your experience and target job.
                  </p>
                  <Link href="/features/cv-writer" className="text-indigo-600 hover:text-indigo-800 font-medium">
                    Learn more →
                  </Link>
                </div>
              </div>
              
              {/* AI Fitness Plan */}
              <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
                <div className="p-6">
                  <div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold mb-2">AI Fitness Plan</h3>
                  <p className="text-gray-600 mb-4">
                    Get personalized workout routines and diet plans tailored to your goals and preferences.
                  </p>
                  <Link href="/features/fitness" className="text-indigo-600 hover:text-indigo-800 font-medium">
                    Learn more →
                  </Link>
                </div>
              </div>
              
              {/* Grammar Checker */}
              <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
                <div className="p-6">
                  <div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold mb-2">Grammar Checker</h3>
                  <p className="text-gray-600 mb-4">
                    Improve your writing with advanced grammar and style suggestions for clear, error-free content.
                  </p>
                  <Link href="/features/grammar" className="text-indigo-600 hover:text-indigo-800 font-medium">
                    Learn more →
                  </Link>
                </div>
              </div>
              
              {/* Plagiarism Checker */}
              <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
                <div className="p-6">
                  <div className="w-12 h-12 bg-indigo-100 rounded-lg flex items-center justify-center mb-4">
                    <svg className="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 21h7a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v11m0 5l4.879-4.879m0 0a3 3 0 104.243-4.242 3 3 0 00-4.243 4.242z"></path>
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold mb-2">Plagiarism Checker</h3>
                  <p className="text-gray-600 mb-4">
                    Verify the originality of your content with our comprehensive plagiarism detection tool.
                  </p>
                  <Link href="/features/plagiarism" className="text-indigo-600 hover:text-indigo-800 font-medium">
                    Learn more →
                  </Link>
                </div>
              </div>
            </div>
            
            <div className="text-center mt-12">
              <Link href="/features" className="inline-block bg-indigo-600 text-white hover:bg-indigo-700 py-3 px-8 rounded-lg font-semibold transition-colors">
                View All Features
              </Link>
            </div>
          </div>
        </section>
        
        {/* How It Works */}
        <section className="py-16">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">How It Works</h2>
              <p className="text-xl text-gray-600 max-w-2xl mx-auto">
                Get started with InnoGenius.ai in just a few simple steps.
              </p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
              <div className="text-center">
                <div className="w-16 h-16 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl font-bold text-indigo-600">1</span>
                </div>
                <h3 className="text-xl font-bold mb-2">Choose a Tool</h3>
                <p className="text-gray-600">
                  Select from our range of AI-powered tools designed to solve specific problems.
                </p>
              </div>
              
              <div className="text-center">
                <div className="w-16 h-16 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl font-bold text-indigo-600">2</span>
                </div>
                <h3 className="text-xl font-bold mb-2">Input Your Content</h3>
                <p className="text-gray-600">
                  Provide the necessary information or content for the AI to process.
                </p>
              </div>
              
              <div className="text-center">
                <div className="w-16 h-16 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-2xl font-bold text-indigo-600">3</span>
                </div>
                <h3 className="text-xl font-bold mb-2">Get Results</h3>
                <p className="text-gray-600">
                  Receive high-quality, AI-generated results in seconds, ready to use.
                </p>
              </div>
            </div>
          </div>
        </section>
        
        {/* Pricing Overview */}
        <section className="py-16 bg-gray-50">
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-4">Simple, Transparent Pricing</h2>
              <p className="text-xl text-gray-600 max-w-2xl mx-auto">
                Choose the plan that works best for you, from free to unlimited.
              </p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
              {/* Free Plan */}
              <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
                <div className="p-6">
                  <h3 className="text-xl font-bold mb-2">Free Plan</h3>
                  <p className="text-3xl font-bold mb-4">$0<span className="text-sm text-gray-500 font-normal">/month</span></p>
                  <ul className="mb-6 space-y-2">
                    <li className="flex items-center">
                      <svg className="h-5 w-5 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
                      </svg>
                      <span>5 uses total/month</span>
                    </li>
                    <li className="flex items-center">
                      <svg className="h-5 w-5 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
                      </svg>
                      <span>Basic features</span>
                    </li>
                    <li className="flex items-center text-gray-400">
                      <svg className="h-5 w-5 text-gray-400 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path>
                      </svg>
                      <span>Priority support</span>
                    </li>
                  </ul>
                  <Link href="/signup" className="block text-center bg-gray-200 text-gray-800 py-2 px-4 rounded-md hover:bg-gray-300 transition-colors">
                    Get Started
                  </Link>
                </div>
              </div>
              
              {/* Standard Plan */}
              <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow border-2 border-indigo-500 relative">
                <div className="absolute top-0 right-0 bg-indigo-500 text-white px-3 py-1 rounded-bl-lg rounded-tr-lg text-sm font-medium">
                  Popular
                </div>
                <div className="p-6">
                  <h3 className="text-xl font-bold mb-2">Standard Plan</h3>
                  <p className="text-3xl font-bold mb-4">$10<span className="text-sm text-gray-500 font-normal">/month</span></p>
                  <ul className="mb-6 space-y-2">
                    <li className="flex items-center">
                      <svg className="h-5 w-5 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
                      </svg>
                      <span>50 uses/month</span>
                    </li>
                    <li className="flex items-center">
                      <svg className="h-5 w-5 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
                      </svg>
                      <span>All features</span>
                    </li>
                    <li className="flex items-center">
                      <svg className="h-5 w-5 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
                      </svg>
                      <span>Email support</span>
                    </li>
                  </ul>
                  <Link href="/signup" className="block text-center bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 transition-colors">
                    Get Started
                  </Link>
                </div>
              </div>
              
              {/* Premium Plan */}
              <div className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
                <div className="p-6">
                  <h3 className="text-xl font-bold mb-2">Premium Plan</h3>
                  <p className="text-3xl font-bold mb-4">$15<span className="text-sm text-gray-500 font-normal">/month</span></p>
                  <ul className="mb-6 space-y-2">
                    <li className="flex items-center">
                      <svg className="h-5 w-5 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
                      </svg>
                      <span>Unlimited uses</span>
                    </li>
                    <li className="flex items-center">
                      <svg className="h-5 w-5 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
                      </svg>
                      <span>All features</span>
                    </li>
                    <li className="flex items-center">
                      <svg className="h-5 w-5 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
                      </svg>
                      <span>Priority support</span>
                    </li>
                  </ul>
                  <Link href="/signup" className="block text-center bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 transition-colors">
                    Get Started
                  </Link>
                </div>
              </div>
            </div>
            
            <div className="text-center mt-8">
              <Link href="/pricing" className="text-indigo-600 hover:text-indigo-800 font-medium">
                View detailed pricing information →
              </Link>
            </div>
          </div>
        </section>
        
        {/* Email Capture Form */}
        <EmailCaptureForm />
      </main>
      
      <Footer />
    </div>
  );
}
