import React from 'react';

interface AITextDetectorProps {
  className?: string;
}

const AITextDetector: React.FC<AITextDetectorProps> = ({ className = '' }) => {
  return (
    <div className={`p-6 rounded-lg shadow-sm ${className}`}>
      <form className="space-y-4">
        <div>
          <label htmlFor="text-to-analyze" className="block text-sm font-medium text-gray-700 mb-1">
            Text to Analyze
          </label>
          <textarea
            id="text-to-analyze"
            rows={6}
            className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
            placeholder="Paste text here to check if it was generated by AI..."
          ></textarea>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label htmlFor="detection-mode" className="block text-sm font-medium text-gray-700 mb-1">
              Detection Mode
            </label>
            <select
              id="detection-mode"
              className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
            >
              <option value="standard">Standard (Balanced)</option>
              <option value="strict">Strict (Fewer false negatives)</option>
              <option value="lenient">Lenient (Fewer false positives)</option>
              <option value="academic">Academic (Optimized for essays)</option>
            </select>
          </div>
          
          <div>
            <label htmlFor="language" className="block text-sm font-medium text-gray-700 mb-1">
              Language
            </label>
            <select
              id="language"
              className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
            >
              <option value="auto">Auto-detect</option>
              <option value="en">English</option>
              <option value="es">Spanish</option>
              <option value="fr">French</option>
              <option value="de">German</option>
              <option value="it">Italian</option>
              <option value="pt">Portuguese</option>
            </select>
          </div>
        </div>
        
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Detection Options
          </label>
          <div className="flex flex-wrap gap-4">
            <div className="flex items-center">
              <input
                id="detailed-analysis"
                type="checkbox"
                className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                defaultChecked
              />
              <label htmlFor="detailed-analysis" className="ml-2 text-sm text-gray-700">
                Detailed analysis
              </label>
            </div>
            <div className="flex items-center">
              <input
                id="highlight-ai-patterns"
                type="checkbox"
                className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                defaultChecked
              />
              <label htmlFor="highlight-ai-patterns" className="ml-2 text-sm text-gray-700">
                Highlight AI patterns
              </label>
            </div>
            <div className="flex items-center">
              <input
                id="check-perplexity"
                type="checkbox"
                className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                defaultChecked
              />
              <label htmlFor="check-perplexity" className="ml-2 text-sm text-gray-700">
                Check perplexity
              </label>
            </div>
            <div className="flex items-center">
              <input
                id="check-burstiness"
                type="checkbox"
                className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                defaultChecked
              />
              <label htmlFor="check-burstiness" className="ml-2 text-sm text-gray-700">
                Check burstiness
              </label>
            </div>
          </div>
        </div>
        
        <div className="pt-2">
          <button
            type="submit"
            className="w-full bg-indigo-600 text-white py-2 px-4 rounded-md hover:bg-indigo-700 transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
          >
            Detect AI Text
          </button>
          <p className="text-xs text-gray-500 mt-2 text-center">
            This will count as 1 use from your monthly limit
          </p>
        </div>
      </form>
    </div>
  );
};

export default AITextDetector;
